language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer self-update
  - composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin"
  - travis_retry composer install --no-interaction --prefer-source --dev
  - travis_retry mysql -e "CREATE DATABASE scheduler_test;"
  - php tests/_app/yii migrate/up --interactive=0 --migrationPath=src/migrations/
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run --coverage --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml